Fix timezoned timestamps
Copy/pasting the timestamp printed by awslogs currently breaks with:

         awslogs get group --timestamp -s '2016-08-31T02:23:25.000Z' -e '2016-08-31T02:23:38.000Z'

         ================================================================================
         You've found a bug! Please, raise an issue attaching the following traceback
         https://github.com/jorgebastida/awslogs/issues/new
         --------------------------------------------------------------------------------
         Version: 0.6.0
         Python: 2.7.12 (default, Jun 29 2016, 14:05:02)
         [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
         boto3 version: 1.3.1
         Platform: Darwin-15.6.0-x86_64-i386-64bit
         Config: {'output_timestamp_enabled': True, 'output_group_enabled': True, 'end': '2016-08-31T02:23:38.000Z', 'log_group_name': 'group', 'log_stream_name': 'ALL', 'aws_region': 'us-east-1', 'watch': False, 'aws_access_key_id': 'SENSITIVE', 'start': '2016-08-31T02:23:25.000Z', 'aws_profile': 'SENSITIVE', 'filter_pattern': '', 'aws_secret_access_key': 'SENSITIVE', 'output_ingestion_time_enabled': False, 'func': 'list_logs', 'aws_session_token': 'SENSITIVE', 'color_enabled': True, 'output_stream_enabled': True}
         Args: ['/usr/local/bin/awslogs', 'get', 'group', '--timestamp', '-s', '2016-08-31T02:23:25.000Z', '-e', '2016-08-31T02:23:38.000Z']

         Traceback (most recent call last):
           File "/usr/local/lib/python2.7/site-packages/awslogs-0.6.0-py2.7.egg/awslogs/bin.py", line 162, in main
             logs = AWSLogs(**vars(options))
           File "/usr/local/lib/python2.7/site-packages/awslogs-0.6.0-py2.7.egg/awslogs/core.py", line 49, in __init__
             self.start = self.parse_datetime(kwargs.get('start'))
           File "/usr/local/lib/python2.7/site-packages/awslogs-0.6.0-py2.7.egg/awslogs/core.py", line 252, in parse_datetime
             return int(total_seconds(date - datetime(1970, 1, 1))) * 1000
         TypeError: can't subtract offset-naive and offset-aware datetimes
         ================================================================================
         exit status 1

This fixes it!